{% set name = "spade" %}
{% set version = VERSION %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: '..'

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - scons install --prefix=${PREFIX}  # [unix]
    - scons install --prefix=%PREFIX%  # [win]
  entry_points:
    - spade = spade._main:main

requirements:
  host:
    - python
    - pip
    - python-build
    - scons >=4.6
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinx-copybutton >=0.5.1
    - sphinx-design
    - sphinxcontrib-bibtex
  run:
    - python >={{ python_min }}
    - cxx-compiler # [linux or win]
    - hdf5  # [linux or win]
    - scons >=4.6
    - __linux  # [linux]
    - __glibc >=2.28  # [linux]
    - __osx  # [osx]
    - __win  # [win]
    - getopt-win32  # [win]

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - spade

about:
  home: https://re-git.lanl.gov/aea/python-projects/spade
  summary: 'Tool for extracting data from an Abaqus output database (odb) file into a hierarchical data format (hdf5) file'
  license: BSD-3-Clause
  license_file: LICENSE.txt
