{% set name = "spade" %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: '..'

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    - scons install --prefix=${PREFIX}  # [unix]
    - scons install --prefix=%PREFIX%  # [win]
  entry_points:
    - spade = spade._main:main

requirements:
  build:
    - python {{ python }}
    - python-build
    - numpy
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinx-copybutton >=0.5.1
    - sphinx-design
    - sphinxcontrib-bibtex
    - setuptools >=77
    - setuptools_scm >=8
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - hdf5
    - scons >=4.6
    - ld_impl_linux-64         # [linux]
  host:
    - python {{ python }}
    - numpy
    - python-build
    - pip
    - setuptools >=77
    - setuptools_scm >=8
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - hdf5
    - scons >=4.6
    - ld_impl_linux-64         # [linux]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scons >=4.6
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - hdf5
    - ld_impl_linux-64         # [linux]

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - spade
  commands:
    - working_directory=${PWD}
    - cd $SP_DIR/$PKG_NAME
    - pytest -n 4 -vvv -m "not require_third_party"

about:
  home: https://github.com/lanl-aea/spade
  summary: 'Tool for extracting data from an Abaqus output database (odb) file into a hierarchical data format (hdf5) file'
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Prabhu-LANL
    - kbrindley
