workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

include: ".pipeline-common.yml"

stages:
  - test

default:
  tags:
    - windows
    - pn2606796

win-style-guide:
  extends:
    - .win-job-environment
    - .style-guide
  stage: test
  variables:
    environment_file: "style.yml"
    abaqus_command: '--abaqus-command="C:\SIMULIA\Commands\abq2025.bat"'

win-developer-test:
  extends:
    - .win-job-environment
    - .developer-test
  stage: test
  variables:
    abaqus_command: '--abaqus-command="C:\SIMULIA\Commands\abq2025.bat" --abaqus-command="C:\SIMULIA\Commands\abq2024.bat"'

win-conda-build:
  extends:
    - .win-job-environment
  stage: test
  variables:
    environment_file: "conda-build.yml"
    recipe_directory: "recipe"
  script:
    # Job variables
    - Write-Output $recipe_directory
    - if ([string]::IsNullOrEmpty($recipe_directory)) { exit 1 }
    # Job commands
    - $env:VERSION=python -m setuptools_scm
    - conda mambabuild $recipe_directory --channel conda-forge --no-anaconda-upload --croot $env:temp --output-folder conda-bld
