workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

include: ".pipeline-common.yml"

stages:
  - test

default:
  tags:
    - rocinante
    - shell
  # Required for HPC Jacamar Runner
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov

hpc-developer-test:
  extends:
    - .nix-job-environment
    - .developer-test
  stage: test
  variables:
    conda_installation: "/udsl/udsl1/hpcsoft/common/x86_64/anaconda/2024.10-python-3.12"
    abaqus_command: "--abaqus-command=/usr/projects/ea/abaqus/Commands/abq2025 --abaqus-command=/usr/projects/ea/abaqus/Commands/abq2024 --abaqus-command=/usr/projects/ea/abaqus/Commands/abq2023 --abaqus-command=/usr/projects/ea/abaqus/Commands/abq2022"
