workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

include: ".pipeline-common.yml"

stages:
  - test

default:
  tags:
    - macos
    - pn2301275

mac-style-guide:
  extends:
    - .nix-job-environment
    - .style-guide
  stage: test
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    environment_file: "style.yml"
    abaqus_command: ''

mac-developer-test:
  extends:
    - .nix-job-environment
    - .developer-test
  stage: test
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    abaqus_command: ''

mac-conda-build:
  extends:
    - .nix-job-environment
    - .conda-build
  stage: test
  variables:
    conda_installation: "/Users/gitlab-runner/anaconda3"
    environment_file: "conda-build.yml"
    recipe_directory: "recipe"
