#! /usr/bin/env python

import pathlib

# Inherit the parent construction environment
Import("env", "abaqus_environments")

build_directory = pathlib.Path(Dir(".").abspath)

pytest_source_list = [
    "pyproject.toml",
]

# Common task options
pytest_command = "cd ${package_dir} && pytest -n 4"

# Unit tests
pytest_node = env.Command(
    target=["coverage.xml", Dir("./coverage")],
    source=pytest_source_list,
    action=[
        "${pytest_command} -vvv -m 'not systemtest' ${coverage}",
    ],
    pytest_command=pytest_command,
    coverage="--cov --cov-report=term --cov-report=xml:${TARGETS[0].abspath} --cov-report=html:${TARGETS[1].abspath}",
)
env.Alias("pytest", pytest_node)
env.Clean("pytest", Dir("./coverage"))
env.Alias("regression", pytest_node)
# Always run pytests in place of a complete source list
env.AlwaysBuild(pytest_node)

# System tests
matrix = (
    ("and not require_third_party", "python3", {"python3": env}),
    ("and require_third_party", "abaqus", abaqus_environments),
)
for extra_markers, alias_suffix, environments in matrix:
    for name, environment in environments.items():
        source = pytest_source_list + [env["package_dir"] / "tests/test_system.py"]
        systemtest_node = env.Command(
            target=[f"systemtest_{name}_results.xml"],
            source=source,
            action=[
                (
                    "${pytest_command} -v --no-showlocals -m 'systemtest ${extra_markers}' --tb=short --cache-clear "
                    "--system-test-dir=${system_test_directory} --junitxml=${TARGETS[0].abspath}"
                ),
            ],
            pytest_command=pytest_command,
            extra_markers=extra_markers,
            system_test_directory=build_directory / name,
        )
        env.Alias("systemtest", systemtest_node)
        env.Alias(f"systemtest_{alias_suffix}", systemtest_node)
        env.Clean(systemtest_node, [Dir(build_directory)])
        env.Alias("regression", systemtest_node)
        env.AlwaysBuild(systemtest_node)
