#! /usr/bin/env python
import os
import pathlib
import platform
import shutil
import sys

import _utilities
import _settings


# Project command line options
AddOption(
    "--build-dir",
    default="build",
    nargs=1,
    type="string",
    action="store",
    metavar="DIR",
    help="SCons build (variant) root directory. Relative or absolute path. (default: '%default')",
)
AddOption(
    "--abaqus-command",
    default="abaqus",
    nargs=1,
    type="string",
    action="store",
    help="Abaqus executable relative or absolute path (default: '%default')",
)
AddOption(
    "--recompile",
    default=False,
    action="store_true",
    help="Recompile the spade executable. Implemented as an AlwaysBuild when True (default: '%default')",
)

# Project environment
user_env = os.environ.copy()
conda_prefix = pathlib.Path(user_env["CONDA_PREFIX"])
env = Environment(
    ENV=user_env,
    recompile=GetOption("recompile"),
    project_name_cpp=_settings._project_name_cpp,
)
if "CXX" in user_env and not "CXX" in env:
    env["CXX"] = user_env["CXX"]
if env["CXX"] == "$CC":
    env["CXX"] = env["CC"]
if platform.system().lower() == "windows":
    conda_include_path = next((path for path in conda_prefix.rglob("**/Library/Include")), None)
    if conda_include_path is not None:
        env["CXXFLAGS"] = env["CXXFLAGS"] + f" /I{conda_include_path.as_posix()} /std:c++17"
    else:
        sys.exit("Could not find the expected Windows CONDA_PREFIX include path")
    _compiler_flags = _settings._compiler_flags_msvc
    _link_flags = _settings._link_flags_msvc
else:
    _compiler_flags = _settings._compiler_flags_gcc
    _link_flags = _settings._link_flags_gcc

build_directory = pathlib.Path(GetOption("build_dir"))
abaqus_command = shutil.which(GetOption("abaqus_command"), path=env["ENV"]["PATH"])

# Abaqus and system settings
abaqus_version = _utilities.abaqus_official_version(abaqus_command)
abaqus_installation, abaqus_code_bin, abaqus_code_include = _utilities.return_abaqus_code_paths(abaqus_command)
env["abaqus_make_command"] = f"{abaqus_command} make job={_settings._project_name_cpp}.cpp"

# Compiler options and settings
if platform.system().lower() == "windows":
    env["odb_flags"] = _compiler_flags + f" /I{abaqus_code_include.as_posix()} /I{abaqus_installation.as_posix()}"
    env["abaqus_link_flags"] = _link_flags
else:
    compiler_string = shutil.which(env["CXX"], path=env["ENV"]["PATH"])
    if compiler_string is None:
        sys.exit(f"Could not find CXX compiler '{env['CXX']}' on PATH '{env['ENV']['PATH']}'")
    else:
        compiler_prefix = pathlib.Path(compiler_string).parent.parent
    compiler_lib = compiler_prefix / "lib"
    compiler_include = compiler_prefix / "include"
    if not compiler_lib.exists() or not compiler_include.exists():
        sys.exit(
            f"Did not find 'lib' or 'include' for compiler '{env['CXX']}' at '{compiler_lib}' or '{compiler_include}'"
        )
    env["odb_flags"] = (
        _compiler_flags
        + f" -I{abaqus_code_include.as_posix()} -I{abaqus_installation.as_posix()} -I{compiler_include.as_posix()} -I. -I{compiler_lib.as_posix()}"
    )
    env["abaqus_link_flags"] = (
        _link_flags
        + f" -L{compiler_lib.as_posix()} -Wl,-rpath,{abaqus_code_bin.as_posix()},-rpath,{compiler_lib.as_posix()}"
    )
# TODO: May wish to confirm that h5c++ is definitely in the same place as gpp (lib and include)
h5_header_file = "H5Cpp.h"
h5_include_path = next((path.parent for path in conda_prefix.rglob(f"**/{h5_header_file}")), None)
if h5_include_path is None:
    sys.exit(f"Could not find H5 header file '{h5_header_file}' in '{conda_prefix}'")
h5_flags = f" -I{h5_include_path.as_posix()}"
if platform.system().lower() == "windows":
    env["SPADEOBJECTCXXFLAGS"] = env["odb_flags"] + h5_flags + " /std:c++17"
else:
    env["SPADEOBJECTCXXFLAGS"] = env.ParseFlags(env["odb_flags"] + h5_flags)

# Configure tasks
sconsign_file = build_directory / ".sconsign.dblite"
env.SConsignFile(sconsign_file)
env.SConscript("SConscript", variant_dir=build_directory, exports="env", duplicate=True)

# Add aliases to help message so users know what build target options are available
# This must come *after* all expected Alias definitions and SConscript files.
from SCons.Node.Alias import default_ans  # noqa: E402

alias_help = "\nTarget Aliases:\n"
for alias in default_ans:
    alias_help += f"    {alias}\n"
try:
    Help(alias_help, append=True, keep_local=True)
except TypeError:
    Help(alias_help, append=True)
