package:
  name: spade
  version: {{ VERSION }}

about:
  home: https://re-git.lanl.gov/aea/python-projects/spade
  summary: 'Tool for extracting data from an Abaqus output database (odb) file into a hierarchical data format (hdf5) file'

source:
  path: '..'

build:
  noarch: python
  script: {{ PYTHON }} setup.py install
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  script:
    # Build and install Conda package
    - $PYTHON -m build --no-isolation
    - $PYTHON -m pip install dist/$PKG_NAME-$PKG_VERSION.tar.gz --no-deps --ignore-installed -v --no-build-isolation
    - $PYTHON -m pip show $PKG_NAME
    # Build man page and HTML documentation to bundle in Conda package
    - scons man html
    - $PYTHON package_documentation.py
  ignore_run_exports:
    - python_abi
  entry_points:
    - spade = spade._main:main

requirements:
  build:
    - python {{ python }}
    - numpy
    - sphinx >=5.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx_rtd_theme >=1
    - sphinxcontrib-bibtex
    - setuptools_scm[toml] >=6.2
    - {{ compiler('cxx') }}
    - hdf5
    - scons
    - sysroot_linux-64 >=2.17
    - ld_impl_linux-64
  host:
    - python {{ python }}
    - numpy
    - python-build
    - pip
    - setuptools >=62
    - setuptools_scm[toml] >=6.2
    - {{ compiler('cxx') }}
    - hdf5
    - scons
    - sysroot_linux-64 >=2.17
    - ld_impl_linux-64
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scons
    - {{ compiler('cxx') }}
    - hdf5
    - sysroot_linux-64 >=2.17
    - ld_impl_linux-64

test:
  requires:
    - pytest
    - pytest-xdist
  imports:
    - spade
  commands:
    # Test as-installed project unit tests
    - cd $SP_DIR/$PKG_NAME
    - pytest -vvv -n 4 -m "not systemtest"
    - pytest -v -n 4 -m "systemtest" --tb=short
